# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.18

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.18.1/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.18.1/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/tuqiang/2.github/TinyJPEGDecoder

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/tuqiang/2.github/TinyJPEGDecoder

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.18.1/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.18.1/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/tuqiang/2.github/TinyJPEGDecoder/CMakeFiles /Users/tuqiang/2.github/TinyJPEGDecoder//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/tuqiang/2.github/TinyJPEGDecoder/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Tiny_JPEG_Decoder

# Build rule for target.
Tiny_JPEG_Decoder: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Tiny_JPEG_Decoder
.PHONY : Tiny_JPEG_Decoder

# fast build rule for target.
Tiny_JPEG_Decoder/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tiny_JPEG_Decoder.dir/build.make CMakeFiles/Tiny_JPEG_Decoder.dir/build
.PHONY : Tiny_JPEG_Decoder/fast

src/jidctflt.o: src/jidctflt.c.o

.PHONY : src/jidctflt.o

# target to build an object file
src/jidctflt.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tiny_JPEG_Decoder.dir/build.make CMakeFiles/Tiny_JPEG_Decoder.dir/src/jidctflt.c.o
.PHONY : src/jidctflt.c.o

src/jidctflt.i: src/jidctflt.c.i

.PHONY : src/jidctflt.i

# target to preprocess a source file
src/jidctflt.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tiny_JPEG_Decoder.dir/build.make CMakeFiles/Tiny_JPEG_Decoder.dir/src/jidctflt.c.i
.PHONY : src/jidctflt.c.i

src/jidctflt.s: src/jidctflt.c.s

.PHONY : src/jidctflt.s

# target to generate assembly for a file
src/jidctflt.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tiny_JPEG_Decoder.dir/build.make CMakeFiles/Tiny_JPEG_Decoder.dir/src/jidctflt.c.s
.PHONY : src/jidctflt.c.s

src/loadjpeg.o: src/loadjpeg.c.o

.PHONY : src/loadjpeg.o

# target to build an object file
src/loadjpeg.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tiny_JPEG_Decoder.dir/build.make CMakeFiles/Tiny_JPEG_Decoder.dir/src/loadjpeg.c.o
.PHONY : src/loadjpeg.c.o

src/loadjpeg.i: src/loadjpeg.c.i

.PHONY : src/loadjpeg.i

# target to preprocess a source file
src/loadjpeg.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tiny_JPEG_Decoder.dir/build.make CMakeFiles/Tiny_JPEG_Decoder.dir/src/loadjpeg.c.i
.PHONY : src/loadjpeg.c.i

src/loadjpeg.s: src/loadjpeg.c.s

.PHONY : src/loadjpeg.s

# target to generate assembly for a file
src/loadjpeg.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tiny_JPEG_Decoder.dir/build.make CMakeFiles/Tiny_JPEG_Decoder.dir/src/loadjpeg.c.s
.PHONY : src/loadjpeg.c.s

src/tinyjpeg.o: src/tinyjpeg.c.o

.PHONY : src/tinyjpeg.o

# target to build an object file
src/tinyjpeg.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tiny_JPEG_Decoder.dir/build.make CMakeFiles/Tiny_JPEG_Decoder.dir/src/tinyjpeg.c.o
.PHONY : src/tinyjpeg.c.o

src/tinyjpeg.i: src/tinyjpeg.c.i

.PHONY : src/tinyjpeg.i

# target to preprocess a source file
src/tinyjpeg.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tiny_JPEG_Decoder.dir/build.make CMakeFiles/Tiny_JPEG_Decoder.dir/src/tinyjpeg.c.i
.PHONY : src/tinyjpeg.c.i

src/tinyjpeg.s: src/tinyjpeg.c.s

.PHONY : src/tinyjpeg.s

# target to generate assembly for a file
src/tinyjpeg.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Tiny_JPEG_Decoder.dir/build.make CMakeFiles/Tiny_JPEG_Decoder.dir/src/tinyjpeg.c.s
.PHONY : src/tinyjpeg.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Tiny_JPEG_Decoder"
	@echo "... src/jidctflt.o"
	@echo "... src/jidctflt.i"
	@echo "... src/jidctflt.s"
	@echo "... src/loadjpeg.o"
	@echo "... src/loadjpeg.i"
	@echo "... src/loadjpeg.s"
	@echo "... src/tinyjpeg.o"
	@echo "... src/tinyjpeg.i"
	@echo "... src/tinyjpeg.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

